version: '2'

services:
  web:
    image: {{cookiecutter.project_slug}}_web
    build: ./web/
    # Expose ports without publishing them
    ports:
      - "8000:8000"
    links:
      - db:db
    env_file: .env.dev
    volumes:
      - ./web:/usr/src/app
    depends_on:
      - db
    command: /run_server.sh local

  db:
    image: {{cookiecutter.project_slug}}_db
    build: ./db/
    env_file: .env.dev
    volumes:
      - db_{{cookiecutter.project_slug}}_data_dev:/var/lib/postgresql/data:rw
      - db_{{cookiecutter.project_slug}}_backup_dev:/backups
      - web_{{cookiecutter.project_slug}}_public_dev:/public:rw
    # Expose ports without publishing them
    expose:
      - "5432"

volumes:
  db_{{cookiecutter.project_slug}}_data_dev:
    driver: local
  db_{{cookiecutter.project_slug}}_backup_dev:
    driver: local
  web_{{cookiecutter.project_slug}}_public_dev:
    driver: local